### ISSUE TITLE
release 2.99_005 checklist

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#740]
Template checklist for 2.99_005.  

- [x] Bump versions across all files
- [x] Blog post for release - https://biodiverse-analysis-software.blogspot.com/2019/08/version-299005-released-version-3-is.html 
- [x] Update versions.txt file
- [x] Update news on github.io site
- [x] Post exe versions to downloads site
- [x] Update link in Downloads wiki page
- [x] Update SpatialConditions wiki
- [x] Update Indices wiki
- [x] Update ReleaseNotes wiki
- [x] Blog for issue #161 - https://biodiverse-analysis-software.blogspot.com/2019/08/export-cluster-analyses-to-shapefiles.html
