### ISSUE TITLE
Release 3 checklist

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#743]
- [x] Bump versions across all files
- [x] Blog post - https://biodiverse-analysis-software.blogspot.com/2019/09/biodiverse-version-3.html
- [x] Update versions.txt file
- [x] Update news on github.io site (need to link to blog post)
- [x] Post exe versions to downloads site
- [x] Update link in Downloads wiki page
- [x] Update SpatialConditions wiki
- [x] Update Indices wiki
- [x] Update ReleaseNotes wiki
- [x] Update Task:: files on CPAN
- [x] Tag release

**Comment by shawnlaffan** [comment]
Done.
