### ISSUE TITLE
Release 4 checklist

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#799]
- [x] Bump versions across all files
- [x] Blog post - https://biodiverse-analysis-software.blogspot.com/2022/11/biodiverse-version-40-has-been-released.html
- [x] Update versions.txt file
- [x] Update news on github.io site (need to link to blog post)
- [x] Post exe versions to downloads site
- [x] Update link in Downloads wiki page
- [x] Update SpatialConditions wiki
- [x] Update Indices wiki
- [x] Update ReleaseNotes wiki
- [x] Deprecate Task:: files on CPAN (they have been superseded by the cpanfile)
- [x] Tag release
- [x] sign windows exe
- [x] Update/check example data

**Comment by shawnlaffan** [comment]
And done.
