### ISSUE TITLE
Release 4.1 checklist

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#847]
- [x] Bump versions across all files
- [x] Blog post - https://biodiverse-analysis-software.blogspot.com/2023/02/biodiverse-version-41-has-been-released.html
- [x] Update versions.txt file
- [x] Update news on github.io site (need to link to blog post)
- [x] Post exe versions to downloads site
- [x] Update link in Downloads wiki page
- [x] Update ReleaseNotes wiki
- [x] Tag release
- [x] sign windows exe
