### ISSUE TITLE
Release 4.2 checklist

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#854]
- [x] Bump versions across all files
- [x] Update versions.txt file
- [x] Update ReleaseNotes wiki
- [x] Tag release
- [x] sign windows exe
- [x] Post exe versions to downloads site
- [x] Update link in Downloads wiki page
- [x] Blog post  - https://biodiverse-analysis-software.blogspot.com/2023/03/biodiverse-version-42-has-been-released.html
- [x] Update news on github.io site (need to link to blog post)
- [x] Post to mailing list

**Comment by shawnlaffan** [comment]
All tasks done, closing issue.
